### PR TITLE
Feat: #60 added hp to user stats adjusted attack method and fixed som…

### LINKED ISSUE #60: [Feature]: Get user hp from users model
### Feature type

New Feature

### Description

Currently, user hp is hardcoded in fights model. Add hp in user model in users and pass it to fights. At this state, add simple hp capped at x amount. Later we can think about adding healing

### PR DESCRIPTION
**Pull request by marcin-nedza**
…e tests

### CODE REVIEW

File: src/modules/fights/attack/index.ts [hunk 1]
```diff
@@ -69,45 +67,38 @@ export default class Controller extends ControllerFactory<EModules.Fights> {
...
 
     // player attack
-    this.applyDamage(target, playerdamage!);
+    await this.applyDamage(target, playerdamage!);
 
     actions.push({
       character: userId,
       action: EAction.Attack,
       target: target.character._id,
       value: -5,
```
Comment (RandomUsername12222) [inline src/modules/fights/attack/index.ts]: Forgot to remove hardcodded default value

Comment (RandomUsername12222) [reply src/modules/fights/attack/index.ts]: I'll fix it

**Review by RandomUsername12222 — APPROVED** [review]
